version: 2
services:
  - type: web
    name: backend-osra
    env: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    region: ohio
    plan: free
    envVars:
      - key: PORT
        value: 3003
    healthCheckPath: /ocrRoutes/ping
    buildFilter:
      paths:
        - server.js
        - routes/**/*.js
        - package.json